# Validation Mode Protocols

## Final Menu Options (Validation Mode)

After completing integrity validation, present this menu to the user:

```
Validation complete - What would you like to do?

[R] Re-run validation (after corrections)
[P] Launch Party Mode to discuss an issue
[M] Switch to Update mode to fix
[E] Export the validation report
[Q] Exit the workflow
```

### Menu Execution Rules

- ALWAYS halt and wait for user input
- This is the FINAL step of Validate mode — no automatic progression

### Menu Handling Logic

**[R] Re-run:** Re-run validation from beginning
- Action: Return to step 1 (Temporal Coherence Check)
- Use case: User has made corrections and wants to verify

**[P] Party Mode:** Discuss specific issue with multiple perspectives
- Action: Invoke Party Mode with specified issue
- Participants: Timeline Guardian, Cartographer, Archivist, Keeper of Souls, Thematic Weaver
- After discussion: Redisplay menu

**[M] Update:** Transition to Edit mode to fix issues
- Action: Display "Switching to Update mode..."
- Load: `../steps-e/step-e-01-trigger.md`
- Begin update workflow to correct identified issues

**[E] Export:** Generate validation report file
- Action: Create markdown report at `{bibleFolder}/validation-report-{date}.md`
- Report contents:
  - Executive summary
  - All issues by category
  - Severity breakdown
  - Recommended fixes
  - Party Mode discussions (if any)
- After export: Redisplay menu

**[Q] Exit:** Exit workflow
- Action: Display "Validation complete. See you soon, guardian of stories!"
- Terminate session

**Any other input:** Help user understand options, then redisplay menu

## Validation Report Template

When user selects [E] Export, generate:

```markdown
# Validation Report - Narrative Bible

**Date:** [YYYY-MM-DD HH:MM]
**Projet:** [Project name]
**Files analyzed:** [list all bible files]

---

## Executive Summary

| Category | Checks | Issues | Status |
|-----------|---------------|--------|--------|
| Temporal | [N] | [N] | ✅/⚠️/❌ |
| Spatial | [N] | [N] | ✅/⚠️/❌ |
| Objects | [N] | [N] | ✅/⚠️/❌ |
| Characters | [N] | [N] | ✅/⚠️/❌ |
| Thematic | [N] | [N] | ✅/⚠️/❌ |

**Overall status:** [✅ VALID / ⚠️ WARNINGS / ❌ CRITICAL ISSUES]

---

## Critical Issues

[Issues that must be fixed]

### Issue #1: [Title]
- **Category:** [Temporal/Spatial/Object/Character/Thematic]
 - **Description:** [Detailed description]
 - **Evidence:**
  - [Dimension A] states: [X]
  - [Dimension B] states: [Y]
 - **Suggestion:** [How to fix]
 - **Impact:** [What breaks if not fixed]

---

## Warnings

[Issues that should be addressed]

[Same format as above]

---

## Minor Issues

[Optional fixes]

[Same format as above]

---

## Recommendations

1. **Immediate priority:** [Critical issues to fix first]
2. **To monitor:** [Warnings to monitor]
3. **Suggested improvements:** [Optional enhancements]

---

## Party Mode Discussions

[If Party Mode was invoked]

### Discussion: [Issue Title]
**Participants:** Timeline Guardian, Cartographer, Archivist, Keeper of Souls, Thematic Weaver

**Perspectives:**
- **Timeline Guardian:** [Their view]
- **Cartographer:** [Their view]
- **Archivist:** [Their view]
- **Keeper of Souls:** [Their view]
- **Thematic Weaver:** [Their view]

**Recommended resolution:** [Consensus solution]

---

*Generated by the Bible Guardian - Living Bible Validation System*
```

## Transition Protocols

### From Validation to Edit Mode

When user selects [M] to fix issues:

1. Display transition message: "Switching to Update mode..."
2. Preserve validation context:
   - Attach validation report to session
   - Flag issues as "to be resolved"
3. Load Edit mode trigger step
4. Begin extraction with validation context

### Re-validation After Corrections

When user selects [R] after making corrections:

1. Clear previous validation results
2. Re-run all 5 coherence checks
3. Compare with previous results:
   - Highlight resolved issues
   - Flag any new issues
   - Note unchanged issues
4. Generate updated report

## Success Criteria

Validation mode is successful when:

**User knows the state of their bible:**
 - Clear verdict (VALID/WARNINGS/CRITICAL ISSUES)
- All issues documented with severity
- Recommended fixes provided

**Clear path forward:**
- Options presented for each possible action
- Transitions to other modes work smoothly
- Reports can be exported for reference

**Quality assurance:**
- All 5 check categories executed
- No issues ignored without user consent
- Party Mode available for complex cases

## Related References

- **Integrity Check Definitions:** See `integrity-check-protocols.md`
- **Step Implementation:** See `step-v-02-integrity.md`
- **Edit Mode Protocols:** See `bible-edit-protocols.md`
